# Generated by Django 3.2.5 on 2023-05-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_reviewrating_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
